### ISSUE TITLE
Some components in frontend do not exist

### ISSUE THREAD

**Issue by R4YM3** [Byont-Ventures/Hackathon#21]
See attached screenshot:

File: testpage.tsx

<img width="1177" alt="Screenshot 2022-11-28 at 20 48 02" src="https://user-images.githubusercontent.com/4108685/204367468-c01ac361-4834-4a4b-a656-38797825cd8a.png">

`npm run build` will fail.

**Comment by jasperverbeet** [comment]
Thanks for reporting this @R4YM3, @SebastiaanCrisan if I remember correctly, this page isn't used anymore, right? Can we delete it...? See PR below.
